server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2
        - id: course_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/courses/**
          filters:
            - StripPrefix=2
        - id: assignment_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/assignments/**
          filters:
            - StripPrefix=2

        - id: file_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2

        - id: communication_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/communications/**
          filters:
            - StripPrefix=2

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
              - PUT
              - DELETE