server:
  port: ${APP_PORT}

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2
        - id: course_service
          uri: ${COURSE_SERVICE_URI}
          predicates:
            - Path=${app.api-prefix}/courses/**
          filters:
            - StripPrefix=2
        - id: assignment_service
          uri: ${ASSIGNMENT_SERVICE_URI}
          predicates:
            - Path=${app.api-prefix}/assignments/**
          filters:
            - StripPrefix=2

        - id: file_service
          uri: ${FILE_SERVICE_URI}
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2

        - id: communication_service
          uri: ${COMMUNICATION_SERVICE_URI}
          predicates:
            - Path=${app.api-prefix}/communications/**
          filters:
            - StripPrefix=2

        - id: notification_service
          uri: ${NOTIFICATION_SERVICE_URI}
          predicates:
            - Path=${app.api-prefix}/notifications/**
          filters:
            - StripPrefix=2

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
              - PUT
              - DELETE
