server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2
        - id: course_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/courses/**
          filters:
            - StripPrefix=2
        - id: file_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/files/**
          filters:
            - StripPrefix=2