apiVersion: apps/v1
kind: Deployment
metadata:
    name: kowl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kowl
    template:
        metadata:
            labels:
                app: kowl
        spec:
            containers:
                - name: kowl
                  image: quay.io/cloudhut/kowl:master
                  ports:
                      - containerPort: 8080
                  env:
                      - name: KAFKA_BROKERS
                        value: "kafka:29092" # Update with your Kafka broker address
---
apiVersion: v1
kind: Service
metadata:
    name: kowl
spec:
    selector:
        app: kowl
    ports:
        - name: http
          protocol: TCP
          port: 8090
          targetPort: 8080
    type: LoadBalancer # You can use LoadBalancer if your cluster supports it
