server:
    port: ${APP_PORT}
    servlet:
        context-path: /courses

spring:
    application:
        name: course-service
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: -1
            retries: 1
            properties:
                enable:
                    idempotence: true
                    max.in.flight.requests.per.connection: 5
        consumer:
            value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
            auto-offset-reset: earliest
app:
    services:
        user: ${USER_SERVICE_URI}
