server:
  port: 8082
  servlet:
    context-path: /courses

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/datn?currentSchema=course_schema&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable:
          idempotence: true
          max.in.flight.requests.per.connection: 5
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
app:
  services:
    user: http://localhost:8088/users