server:
  port: 8085
  servlet:
    context-path: /communications

spring:
  application:
    name: communications-service
  datasource:
    url: jdbc:postgresql://localhost:5555/communications?&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  services:
    user: http://localhost:8088/users