server:
  port: 8081
  servlet:
    context-path: /users

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/datn?currentSchema=user_schema&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true

security:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d4
    access-token-expiration: 86400000
    refresh-token-expiration: 604800000