server:
    port: ${APP_PORT}
    servlet:
        context-path: /users

spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
security:
    jwt:
        secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d4
        access-token-expiration: 86400000
        refresh-token-expiration: 604800000
