apiVersion: apps/v1
kind: Deployment
metadata:
    name: debezium
spec:
    replicas: 1
    selector:
        matchLabels:
            app: debezium
    template:
        metadata:
            labels:
                app: debezium
        spec:
            containers:
                - name: debezium
                  image: debezium/connect
                  ports:
                      - containerPort: 8083
                  env:
                      - name: BOOTSTRAP_SERVERS
                        value: kafka:29092
                      - name: GROUP_ID
                        value: "1"
                      - name: CONFIG_STORAGE_TOPIC
                        value: my_connect_configs
                      - name: OFFSET_STORAGE_TOPIC
                        value: my_connect_offsets
                      - name: STATUS_STORAGE_TOPIC
                        value: my_connect_statuses
---
apiVersion: v1
kind: Service
metadata:
    name: debezium
spec:
    selector:
        app: debezium
    ports:
        - name: http
          protocol: TCP
          port: 8083
          targetPort: 8083
    type: LoadBalancer
