apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
spec:
    replicas: 3
    selector:
        matchLabels:
            app: db
    template:
        metadata:
            labels:
                app: db
        spec:
            containers:
                - name: db
                  image: "debezium/example-postgres"
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5432
                  envFrom:
                      - configMapRef:
                            name: postgres-secret

            #       volumeMounts:
            #           - mountPath: /var/lib/postgresql/data
            #             name: postgresdata
            # volumes:
            #     - name: postgresdata
            #       persistentVolumeClaim:
            #           claimName: postgres-volume-claim
