apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-volume-claim
    labels:
        app: db
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
