kind: Service
apiVersion: v1
metadata:
    name: apaches-published
spec:
    ports:
        - name: http
          protocol: TCP
          port: 8090
          targetPort: 8080
    selector:
        app: kowl
    type: LoadBalancer
